### ISSUE TITLE
testserver: broken with latest build

### ISSUE THREAD

**Issue by boljen** [cockroachdb/cockroach-go#20] opened 2016-12-04 15:06 UTC
ts.WaitForInit(db) blocks indefinitely on my system (Ubuntu 16.04). Is it possible that the latest cockroachdb build breaks the testserver package?

I added a manual break after 5 seconds of iterating and logged the error and stdout/stderr from the testserver;

    func (ts *TestServer) WaitForInit(db *sql.DB) {
		cur, max := 0, 500
		for {
			// We issue a query that fails both on connection errors and on the
			// system database not existing.
			if _, err := db.Query("SHOW DATABASES"); err == nil {
				return
			} else if cur > max {
				log.Println(ts.Stdout())
				log.Println(ts.Stderr())
				panic(err)
			}
			cur++
			time.Sleep(time.Millisecond * 10)
		}
	}

Output (cleaned up):

    2016/12/04 15:52:31 downloading https://s3.amazonaws.com/cockroach/cockroach/cockroach.linux-amd64.9111f757330103a89ccc9ef735d9c37867d71706 to /var/tmp/cockroach.linux-amd64.9111f757330103a89ccc9ef735d9c37867d71706, this may take some time
    2016/12/04 15:52:44 Using automatically-downloaded binary: /var/tmp/cockroach.linux-amd64.9111f757330103a89ccc9ef735d9c37867d71706
    2016/12/04 15:52:44 process 15520 started: /var/tmp/cockroach.linux-amd64.9111f757330103a89ccc9ef735d9c37867d71706 start --logtostderr --insecure --port=0 --http-port=0 --socket=/tmp/cockroach-testserver200397412/.s.PGSQL.26257 --store=/tmp/cockroach-testserver200397412
    waiting for database to initialize
    2016/12/04 15:52:50 CockroachDB node starting at 2016-12-04 15:52:44.767370201 +0100 CET

    --- FAIL: TestRunServer (19.29s)
    panic: pq: database "information_schema" does not exist [recovered]
        panic: pq: database "information_schema" does not exist

Testserver Stdout:

    build:      9111f75 @ 2016/12/04 13:07:50 (go1.7.3)
    admin:      http://m47:45529
    sql:        postgresql://root@m47:40251?sslmode=disable
    socket:     /tmp/cockroach-testserver200397412/.s.PGSQL.26257
    logs:       /tmp/cockroach-testserver200397412/logs
    store[0]:   path=/tmp/cockroach-testserver200397412
    status:     initialized new cluster
    clusterID:  fcbd6d02-c65b-4930-be7f-6859769ab779
    nodeID:     1

Testserver Stderr:

    2016/12/04 15:52:50 I161204 15:52:44.622880 1 cli/start.go:318  CockroachDB 9111f75 (linux amd64, built 2016/12/04 13:07:50, go1.7.3)
    I161204 15:52:44.723164 1 cli/start.go:334  starting cockroach node
    I161204 15:52:44.723274 1 cli/start.go:336  using local environment variables: COCKROACH_MAX_OFFSET
    W161204 15:52:44.723330 1 server/server.go:154  [n?] running in insecure mode, this is strongly discouraged. See --insecure.
    I161204 15:52:44.723455 1 gossip/gossip.go:248  [n?] initial resolvers: []
    W161204 15:52:44.723495 1 gossip/gossip.go:1124  [n?] no resolvers found; use --join to specify a connected node
    I161204 15:52:44.725427 1 storage/engine/rocksdb.go:326  opening rocksdb instance at "/tmp/cockroach-testserver200397412"
    I161204 15:52:44.730046 50 kv/dist_sender.go:302  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
    I161204 15:52:44.759296 1 server/config.go:443  1 storage engine initialized
    I161204 15:52:44.759864 1 server/node.go:419  [n?] store [n0,s0] not bootstrapped
    I161204 15:52:44.761700 63 storage/replica_proposal.go:348  [s1,r1/1:/M{in-ax},@c420276900] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 411350h52m53.761170701s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=2016-12-04 14:52:44.761649824 +0000 UTC]
    I161204 15:52:44.762300 1 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
    I161204 15:52:44.762384 1 server/node.go:348  [n?] **** cluster fcbd6d02-c65b-4930-be7f-6859769ab779 has been created
    I161204 15:52:44.762404 1 server/node.go:349  [n?] **** add additional nodes by specifying --join=m47:40251
    I161204 15:52:44.762671 1 base/node_id.go:62  [n1] NodeID set to 1
    I161204 15:52:44.763014 1 storage/store.go:1223  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
    I161204 15:52:44.763051 1 server/node.go:432  [n1] initialized store [n1,s1]: {Capacity:105555197952 Available:61341224960 RangeCount:1 LeaseCount:1}
    I161204 15:52:44.763078 1 server/node.go:317  [n1] node ID 1 initialized
    I161204 15:52:44.763156 1 gossip/gossip.go:290  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"m47:40251" > attrs:<> locality:<> 
    I161204 15:52:44.763341 1 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
    I161204 15:52:44.763500 1 server/node.go:562  [n1] connecting to gossip network to verify cluster ID...
    I161204 15:52:44.763535 1 server/node.go:582  [n1] node connected via gossip and verified as part of cluster "fcbd6d02-c65b-4930-be7f-6859769ab779"
    I161204 15:52:44.763582 1 server/node.go:367  [n1] node=1: started with [[]=/tmp/cockroach-testserver200397412] engine(s) and attributes []
    I161204 15:52:44.763635 1 sql/executor.go:291  [n1] creating distSQLPlanner with address {tcp m47:40251}
    I161204 15:52:44.765237 28 storage/split_queue.go:103  [n1,split,s1,r1/1:/M{in-ax},@c420277200] splitting at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
    I161204 15:52:44.766902 28 storage/replica_command.go:2369  [n1,split,s1,r1/1:/M{in-ax},@c420277200] initiating a split of this range at key /Table/11 [r2]
    I161204 15:52:44.767156 1 server/server.go:633  [n1] starting http server at m47:45529
    I161204 15:52:44.767177 1 server/server.go:634  [n1] starting grpc/postgres server at m47:40251
    I161204 15:52:44.767198 1 server/server.go:635  [n1] advertising CockroachDB node at m47:40251
    I161204 15:52:44.767261 1 server/server.go:637  [n1] starting postgres server at unix:/tmp/cockroach-testserver200397412/.s.PGSQL.26257
    I161204 15:52:44.768282 106 server/updates.go:158  [n1,updates check] No previous updates check time.
    E161204 15:52:44.775774 29 storage/queue.go:609  [n1,replicate,s1,r1/1:/{Min-Table/11},@c420277200] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.775884 28 storage/queue.go:598  [n1,split,s1,r1/1:/{Min-Table/11},@c420277200] unable to split [n1,s1,r1/1:/{Min-Table/11}] at key "/Table/12/0": key range /Table/12/0-/Table/12/0 outside of bounds of range /Min-/Max
    E161204 15:52:44.775933 110 storage/queue.go:609  [n1,replicate,s1,r1/1:/{Min-Table/11},@c420277200] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.776003 110 storage/queue.go:609  [n1,replicate,s1,r1/1:/{Min-Table/11},@c420277200] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    I161204 15:52:44.776052 28 storage/split_queue.go:103  [n1,split,s1,r2/1:/{Table/11-Max},@c420262480] splitting at keys [/Table/12/0 /Table/13/0 /Table/14/0]
    I161204 15:52:44.776098 28 storage/replica_command.go:2369  [n1,split,s1,r2/1:/{Table/11-Max},@c420262480] initiating a split of this range at key /Table/12 [r3]
    E161204 15:52:44.780195 29 storage/queue.go:609  [n1,replicate,s1,r2/1:/Table/1{1-2},@c420262480] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.780334 28 storage/queue.go:598  [n1,split,s1,r2/1:/Table/1{1-2},@c420262480] unable to split [n1,s1,r2/1:/Table/1{1-2}] at key "/Table/13/0": key range /Table/13/0-/Table/13/0 outside of bounds of range /Table/11-/Max
    E161204 15:52:44.780492 110 storage/queue.go:609  [n1,replicate,s1,r1/1:/{Min-Table/11},@c420277200] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.780576 110 storage/queue.go:609  [n1,replicate,s1,r2/1:/Table/1{1-2},@c420262480] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    I161204 15:52:44.780705 28 storage/split_queue.go:103  [n1,split,s1,r3/1:/{Table/12-Max},@c420262d80] splitting at keys [/Table/13/0 /Table/14/0]
    I161204 15:52:44.780758 28 storage/replica_command.go:2369  [n1,split,s1,r3/1:/{Table/12-Max},@c420262d80] initiating a split of this range at key /Table/13 [r4]
    E161204 15:52:44.784909 29 storage/queue.go:609  [n1,replicate,s1,r3/1:/Table/1{2-3},@c420262d80] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.784938 28 storage/queue.go:598  [n1,split,s1,r3/1:/Table/1{2-3},@c420262d80] unable to split [n1,s1,r3/1:/Table/1{2-3}] at key "/Table/14/0": key range /Table/14/0-/Table/14/0 outside of bounds of range /Table/12-/Max
    I161204 15:52:44.785024 28 storage/split_queue.go:103  [n1,split,s1,r4/1:/{Table/13-Max},@c4201ea900] splitting at keys [/Table/14/0]
    I161204 15:52:44.785064 28 storage/replica_command.go:2369  [n1,split,s1,r4/1:/{Table/13-Max},@c4201ea900] initiating a split of this range at key /Table/14 [r5]
    E161204 15:52:44.785120 110 storage/queue.go:609  [n1,replicate,s1,r1/1:/{Min-Table/11},@c420277200] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.785190 110 storage/queue.go:609  [n1,replicate,s1,r2/1:/Table/1{1-2},@c420262480] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.785246 110 storage/queue.go:609  [n1,replicate,s1,r3/1:/Table/1{2-3},@c420262d80] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.789105 29 storage/queue.go:609  [n1,replicate,s1,r4/1:/Table/1{3-4},@c4201ea900] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.789255 29 storage/queue.go:609  [n1,replicate,s1,r5/1:/{Table/14-Max},@c42024b680] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.789312 110 storage/queue.go:609  [n1,replicate,s1,r1/1:/{Min-Table/11},@c420277200] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.789372 110 storage/queue.go:609  [n1,replicate,s1,r2/1:/Table/1{1-2},@c420262480] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.789426 110 storage/queue.go:609  [n1,replicate,s1,r3/1:/Table/1{2-3},@c420262d80] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    E161204 15:52:44.789477 110 storage/queue.go:609  [n1,replicate,s1,r4/1:/Table/1{3-4},@c4201ea900] purgatory: 0 of 1 store with an attribute matching []; likely not enough nodes in cluster
    I161204 15:52:44.811683 134 sql/event_log.go:95  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:m47:40251} Attrs: Locality:} ClusterID:fcbd6d02-c65b-4930-be7f-6859769ab779 StartedAt:1480863164763543657}
    I161204 15:52:45.353809 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160428, details: https://www.cockroachlabs.com/docs/beta-20160428.html
    I161204 15:52:45.353825 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160505, details: https://www.cockroachlabs.com/docs/beta-20160505.html
    I161204 15:52:45.353833 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160512, details: https://www.cockroachlabs.com/docs/beta-20160512.html
    I161204 15:52:45.353843 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160519, details: https://www.cockroachlabs.com/docs/beta-20160519.html
    I161204 15:52:45.353851 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160526, details: https://www.cockroachlabs.com/docs/beta-20160526.html
    I161204 15:52:45.353860 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160602, details: https://www.cockroachlabs.com/docs/beta-20160602.html
    I161204 15:52:45.353868 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160609, details: https://www.cockroachlabs.com/docs/beta-20160609.html
    I161204 15:52:45.353876 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160616, details: https://www.cockroachlabs.com/docs/beta-20160616.html
    I161204 15:52:45.353885 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160714, details: https://www.cockroachlabs.com/docs/beta-20160714.html
    I161204 15:52:45.353893 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160728, details: https://www.cockroachlabs.com/docs/beta-20160728.html
    I161204 15:52:45.353901 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160908, details: https://www.cockroachlabs.com/docs/beta-20160908.html
    I161204 15:52:45.353909 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160915, details: https://www.cockroachlabs.com/docs/beta-20160915.html
    I161204 15:52:45.353921 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20160929, details: https://www.cockroachlabs.com/docs/beta-20160929.html
    I161204 15:52:45.353930 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20161006, details: https://www.cockroachlabs.com/docs/beta-20161006.html
    I161204 15:52:45.353938 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20161013, details: https://www.cockroachlabs.com/docs/beta-20161013.html
    I161204 15:52:45.353946 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20161027, details: https://www.cockroachlabs.com/docs/beta-20161027.html
    I161204 15:52:45.353956 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20161103, details: https://www.cockroachlabs.com/docs/beta-20161103.html
    I161204 15:52:45.353964 106 server/updates.go:213  [n1,updates check] A new version is available: beta-20161201, details: https://www.cockroachlabs.com/docs/beta-20161201.html

**Comment by boljen** [comment] 2016-12-04 15:21
I'm guessing this is a duplicate of https://github.com/cockroachdb/cockroach/issues/11922.

Has this package been deprecated?

**Comment by tamird** [comment] 2016-12-04 15:23
The commit you're running was a test-only change; is there a previous ref
that doesn't exhibit this problem?

Also, are you running this server with a data directory created by an
earlier version, or is it fresh?

**Comment by tamird** [comment] 2016-12-04 15:24
Not a duplicate; that is issue was closed because it was created by a bug
in our automation. This issue still seems legitimate to me.

**Comment by boljen** [comment] 2016-12-04 17:43
I deleted all relevant /tmp and /var/tmp directories before doing the above test. Unfortunately I have no idea which exact ref introduced the problem.

Could you try to replicate the issue to see whether the issue isn't with my own setup?

**Comment by tamird** [comment] 2016-12-04 22:05
Indeed, I can't seem to reproduce this:
```
$ make test
go test -v -i ./...
github.com/lib/pq/oid
github.com/cockroachdb/cockroach-go/testserver
github.com/lib/pq
go test -v ./...
=== RUN   TestExecuteTx
2016/12/04 17:04:36 Using automatically-downloaded binary: /var/tmp/cockroach.darwin-amd64.43618b6973ffb5e91433895407efab14cf9fba56
2016/12/04 17:04:36 process 29783 started: /var/tmp/cockroach.darwin-amd64.43618b6973ffb5e91433895407efab14cf9fba56 start --logtostderr --insecure --port=0 --http-port=0 --socket=/tmp/cockroach-testserver637974733/.s.PGSQL.26257 --store=/tmp/cockroach-testserver637974733
--- PASS: TestExecuteTx (4.71s)
PASS
ok  	github.com/cockroachdb/cockroach-go/crdb	4.726s
=== RUN   TestRunServer
2016/12/04 17:04:32 downloading https://s3.amazonaws.com/cockroach/cockroach/cockroach.darwin-amd64.43618b6973ffb5e91433895407efab14cf9fba56 to /var/tmp/cockroach.darwin-amd64.43618b6973ffb5e91433895407efab14cf9fba56, this may take some time
2016/12/04 17:04:36 Using automatically-downloaded binary: /var/tmp/cockroach.darwin-amd64.43618b6973ffb5e91433895407efab14cf9fba56
2016/12/04 17:04:36 process 29782 started: /var/tmp/cockroach.darwin-amd64.43618b6973ffb5e91433895407efab14cf9fba56 start --logtostderr --insecure --port=0 --http-port=0 --socket=/tmp/cockroach-testserver445259601/.s.PGSQL.26257 --store=/tmp/cockroach-testserver445259601
--- PASS: TestRunServer (4.63s)
PASS
ok  	github.com/cockroachdb/cockroach-go/testserver	4.648s
```

**Comment by boljen** [comment] 2016-12-05 21:28
You ran the test on darwin but could it be that the issue is linux-specific? I think that the client is unable to connect to the database over the created unix domain socket. The database does start and I can connect to it over the local loopback interface.

**Comment by tamird** [comment] 2016-12-05 21:42
Interesting - this does fail for me in Linux (in docker). @mberhault can you take a look? Indeed seems that something funky is going on with the unix socket.

**Comment by boljen** [comment] 2016-12-05 21:55
I have to hand it to you, those are some fast response times.

**Comment by boljen** [comment] 2016-12-05 22:23
I modified the testserver package to let clients connect through the local loopback interface and everything works fine. I used https://github.com/phayes/freeport to select a random port. Is there a specific reason why file sockets are preferred?

**Comment by mberhault** [comment] 2016-12-06 16:21
the problem was that `WaitForInit` kept trying to run `SHOW DATABASES` until successful.
While this used to work, the query now returns: `pq: database "information_schema" does not exist`. @mjibson may have a better idea why. We use the standard `github.com/lib/pq` in these tests.

Anyway, I've changed `WaitForInit` to just do a `select 1` which should be enough to show that we have a connection. I've also put a 5s limit on it. PR on the way.

As for the reason we did this, it's easier to pick a unique socket and definitely easier to clean up. Since we support sockets, this seemed like the easiest way to go.

**Comment by mberhault** [comment] 2016-12-06 16:24
@tamird: could you try again with an up-to-date libpq?

**Comment by mjibson** [comment] 2016-12-06 18:31
https://github.com/cockroachdb/cockroach/commit/358e8b5589a66f766d8f450f324c7ac56a19c8a1 changed `SHOW DATABASES` to use the `information_schema` table, and my guess is something there is causing that problem. However a `select 1` should be just as good to determine a connection.

**Comment by tamird** [comment] 2016-12-06 18:33
Why does WaitForInit exist at all? `select 1` will always work, regardless
of the initialization of anything.

**Comment by mberhault** [comment] 2016-12-06 18:46
I'm pretty sure it won't work if we haven't successfully established a connection to the database.

@mjibson: we're creating a single-node cluster from scratch. shouldn't `information_schema` exist?

**Comment by boljen** [comment] 2016-12-06 19:25
I made a fork that uses the local loopback instead of file sockets and it works.

https://github.com/boljen/cockroach-go

**Comment by nvanbenschoten** [comment] 2016-12-13 19:27
https://github.com/cockroachdb/cockroach/pull/12324 should have fixed this issue. Is there anything that needs to be updated here before closing?

**Comment by tamird** [comment] 2016-12-13 19:30
I'll kick the build on https://github.com/cockroachdb/cockroach-go/pull/22 once https://github.com/cockroachdb/cockroach/pull/12324 is built; if it's green, we're probs good to go.

**Comment by mberhault** [comment] 2016-12-13 19:33
that should be it. If teamcity turns green after the master build for your change, this can be merged

**Closed** 2016-12-13 22:38 UTC
